Repository openshift/sippy, pull requests merged in 2023-06, with the labels that each got.

#1002 Ignore disruption by default an match api parameter names in ComponentReadiness UI
  sippy-ng/src/component_readiness/CompCapTestRow.js
  sippy-ng/src/component_readiness/CompReadyCapCell.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
  sippy-ng/src/component_readiness/CompReadyTestCell.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompTestRow.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm

#1005 Enable batching for query params (back button)
  sippy-ng/src/index.js
Labels: approved, lgtm

#1006 Add ComponentReadiness UI updates from feedback
  sippy-ng/src/component_readiness/AdvancedOptions.js
  sippy-ng/src/component_readiness/CompReadyProgress.js
  sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/ComponentReadiness.css
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm

#1007 Add search in rows and columns for page 1
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm

#1011 Add Assessment to ComponentReadiness TestReport
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompSeverityIcon.js
Labels: approved, lgtm

#1010 Data consistency issue with variants and proper row and column ordering
  pkg/api/component_report.go
  pkg/apis/api/types.go
Labels: approved, lgtm

#1015 use test id from mapping table
  pkg/api/component_report.go
  pkg/api/component_report_test.go
  pkg/apis/api/types.go
Labels: approved, lgtm

#1012 Use GA dates in component readiness
  pkg/apis/api/types.go
  pkg/releasesync/release_dates.go
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/ReleaseSelector.js
Labels: approved, lgtm

#986 Adjust stacked chart axes
  sippy-ng/src/jobs/JobStackedChart.js
  sippy-ng/src/tests/TestStackedChart.js
Labels: approved, lgtm

#1019 Align test detail rows on top
  sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
  sippy-ng/src/component_readiness/ComponentReadiness.css
Labels: approved, lgtm

#1022 Allow selecting only red components
  sippy-ng/src/component_readiness/CompReadyCell.js
  sippy-ng/src/component_readiness/CompReadyRow.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompSeverityIcon.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm

#1024 Include column filtering when selecting Red Only
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm

#1020 Show test suite and name in component readiness
  pkg/api/component_report.go
  pkg/apis/api/types.go
  sippy-ng/src/component_readiness/CompCapTestRow.js
  sippy-ng/src/component_readiness/CompReadyEnvCapability.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
  sippy-ng/src/component_readiness/CompTestRow.js
Labels: approved, lgtm

#955 TRT-892: Match jobnames, not variants
  pkg/api/job_runs.go
  pkg/api/job_runs_test.go
  pkg/db/query/job_queries.go
  pkg/db/query/test_queries.go
  pkg/testidentification/ocp_variants.go
Labels: approved, lgtm, jira/valid-reference

#1037 Add time range to schema query to cut db cost
  pkg/api/component_report.go
Labels: approved, lgtm

#1039 All searching Pull Requests by PR number
  sippy-ng/src/pull_requests/PullRequestsTable.js
Labels: approved, lgtm

#1048 Update never-stable for 6/21/23
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, lgtm

#1051 Use consistent locale in update-neverstable.sh
  pkg/testidentification/ocp_never_stable.txt
  scripts/update-neverstable.sh
Labels: approved, lgtm

#1049 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#1029 Read excludeVariables from sippy api
  sippy-ng/src/App.js
  sippy-ng/src/component_readiness/CompReadyCapCell.js
  sippy-ng/src/component_readiness/CompReadyCapsCell.js
  sippy-ng/src/component_readiness/CompReadyCell.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
  sippy-ng/src/component_readiness/CompReadyEnvCapability.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyTestCell.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm

#1054 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#1057 Add to/from dates to test report page plus human readable message
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm

#1063 Add hostname if missing when creating URL object
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm

#1064 Refactor release selector
  sippy-ng/src/App.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/ReleaseSelector.js
Labels: approved, lgtm

#1068 Encode curly brances as well
  sippy-ng/src/helpers.js
Labels: approved, lgtm

#1060 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#1067 Widen date window for more human readable date summaries
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm

#1074 Use available context for versions in TestReport
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm
