Repository openshift/sippy, pull requests merged in 2023-07, with the labels that each got.

#1072 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#1089 remove jobs without release impact from sippy main page
  pkg/testidentification/ocp_variants.go
Labels: approved, lgtm

#1092 TRT-1125: add check for test with suite name when missing analysis re…
  pkg/api/job_runs.go
Labels: approved, lgtm, jira/valid-reference

#1093 Sync and show jira incidents on the sippy calendar
  main.go
  pkg/api/jira.go
  pkg/api/releases.go
  pkg/apis/api/types.go
  pkg/apis/jira/v1/types.go
  pkg/db/db.go
  pkg/db/models/models.go
  pkg/jiraloader/jiraloader.go
  pkg/sippyserver/server.go
  sippy-ng/package-lock.json
  sippy-ng/package.json
  sippy-ng/src/releases/PayloadCalendar.js
  sippy-ng/src/releases/PayloadCalendarLegend.js
Labels: approved, lgtm

#1094 Fix bug in the calendaring api
  pkg/api/jira.go
Labels: approved, lgtm

#1077 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#1088 Dedupe junit table results in component readiness
  pkg/api/component_report.go
Labels: approved, lgtm

#1107 More explicit ordering in deduplication of junit table
  pkg/api/component_report.go
Labels: approved, lgtm

#1104 Show statistically significant test summary rows first
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm

#1118 Add architecture filter to rejected-payloads.py script
  scripts/rejected-payloads.py
Labels: approved, lgtm

#1120 TRT-1125: add test names, risk reasons and openbugs for pr comments
  pkg/apis/api/types.go
  pkg/sippyserver/pr_commenting_processor.go
Labels: approved, lgtm, jira/valid-reference
