Repository openshift/sippy, pull requests merged in 2023-09, with the labels that each got.

#1171 Update css-tools to fix security vulnerability
  sippy-ng/package-lock.json
Labels: approved, lgtm

#1172 Remove okd jobs from component readiness report
  pkg/api/component_report.go
Labels: approved, lgtm

#1165 TRT-1122: Get sippy ready for 4.15
  scripts/fetchdata-testgrid.sh
  scripts/fetchdata.sh
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm, jira/valid-reference

#1179 Updating cache to 8 hrs for component readiness
  pkg/sippyserver/server.go
Labels: approved, lgtm

#1181 Narrow scope of Component Readiness defaults
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm

#1175 Allow passing in a jobName for sippy intervals
  pkg/api/jobrunintervals/job_run_intervals.go
  pkg/sippyserver/server.go
  sippy-ng/src/App.js
  sippy-ng/src/prow_job_runs/ProwJobRun.js
Labels: approved, lgtm

#1186 Avoid gorm bug with smallint postgres column
  pkg/db/models/pr_commenting.go
  pkg/github/commenter/ghcommenter.go
  pkg/sippyserver/pr_commenting_processor.go
Labels: approved, lgtm

#1182 Cast argument instead of partitioned field
  pkg/api/component_report.go
Labels: approved, lgtm

#1106 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, needs-ok-to-test, lgtm

#1187 For Component Readiness, open new tab by default
  sippy-ng/src/component_readiness/CompCapRow.js
  sippy-ng/src/component_readiness/CompReadyCapCell.js
  sippy-ng/src/component_readiness/CompReadyCapsCell.js
  sippy-ng/src/component_readiness/CompReadyCell.js
  sippy-ng/src/component_readiness/CompReadyRow.js
  sippy-ng/src/component_readiness/CompReadyTestCell.js
  sippy-ng/src/component_readiness/CompTestRow.js
Labels: approved, lgtm

#1192 Add metric for prow job loading time
  main.go
Labels: approved, lgtm

#1199 Reduce materialized views concurrency from 3 to 2
  pkg/sippyserver/server.go
Labels: approved, lgtm

#1203 Lock the leftmost column and column headers in Component Readiness UI
  sippy-ng/src/component_readiness/ComponentReadiness.css
Labels: approved, lgtm

#1189 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#1191 Parallelize job gcs bucket processing
  config/e2e-openshift.yaml
  e2e-scripts/sippy-e2e-sippy-e2e-setup-commands.sh
  main.go
  pkg/api/health.go
  pkg/prowloader/bigqueryjobs.go
  pkg/prowloader/github/github.go
  pkg/prowloader/prow.go
  test/e2e/util/e2erequest.go
Labels: approved, lgtm

#1200 trt-1167: match consecutive failures for risk analysis reporting
  pkg/sippyserver/pr_commenting_processor.go
  pkg/sippyserver/pr_commenting_processor_test.go
Labels: approved, lgtm, jira/valid-reference

#1208 Ignore recovery jobs in component readiness
  pkg/api/component_report.go
Labels: approved, lgtm

#1209 trt-1167: add check for valid priorRiskAnalysis
  pkg/sippyserver/pr_commenting_processor.go
  pkg/sippyserver/pr_commenting_processor_test.go
Labels: approved, lgtm, jira/valid-reference

#1213 trt-1231: update vsphere-upi regex to handle missed matches
  pkg/testidentification/ocp_variants.go
  pkg/testidentification/ocp_variants_test.go
Labels: approved, lgtm, jira/valid-reference
