Repository openshift/sippy, pull requests merged in 2024-01, with the labels that each got.

#1392 Skip rollback jobs from component readiness
  pkg/api/component_report.go
Labels: approved, lgtm

#1396 Revert "Fix time filter to use ISO format that is required by API"
  sippy-ng/src/datagrid/GridToolbarFilterItem.js
Labels: approved, lgtm

#1408 TRT-1426: Adjust time filter from timestamp to ISO format for release tag query
  sippy-ng/src/releases/ReleasePayloadTable.js
Labels: approved, lgtm, jira/valid-reference

#1402 TRT-1216: sync html and new EventInterval fields from origin
  pkg/apis/api/interval.go
  sippy-ng/src/components/TimelineChart.js
  sippy-ng/src/prow_job_runs/ProwJobRun.js
Labels: approved, lgtm, jira/valid-reference

#1413 TRT-1434: exclude skipped test cases
  pkg/api/component_report.go
Labels: approved, lgtm, jira/valid-reference

#1418 trt-622: add links for grafana and alert manager
  sippy-ng/src/components/Sidebar.js
Labels: approved, lgtm, jira/valid-reference

#1419 trt-622: rename experimental to tools and move disruption and alert l…
  sippy-ng/src/components/Sidebar.js
Labels: approved, lgtm, jira/valid-reference

#1420 TRT-1435: Add a FAQ for component readiness
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/ComponentReadinessHelp.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
Labels: approved, lgtm, jira/valid-reference

#1425 trt-622: use build_clusters capabilities value to drive tools panel i…
  sippy-ng/src/components/Sidebar.js
Labels: approved, lgtm, jira/valid-reference

#1415 TRT-1405: Add context to each CR page to show releases and dates
  sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
  sippy-ng/src/component_readiness/CompReadyEnvCapability.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/Sidebar.js
Labels: approved, lgtm, jira/valid-reference

#1428 Adjust release selector background color
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
Labels: approved, lgtm

#1429 TRT-1435: Add a FAQ explicitly about test renames
  sippy-ng/src/component_readiness/ComponentReadinessHelp.js
Labels: approved, lgtm, jira/valid-reference

#1433 Add mechanism to indicate that a regression is allowed in sippy
  pkg/api/component_report.go
  pkg/regressionallowances/OWNERS
  pkg/regressionallowances/intentional_4.15_regressions.go
  pkg/regressionallowances/types.go
Labels: approved, lgtm

#1439 Dark mode improvements
  sippy-ng/src/App.js
Labels: approved, lgtm

#1432 TRT-1351: Use capability to exclude disruption tests
  pkg/api/component_report.go
Labels: approved, lgtm, jira/valid-reference

#1441 Revert "TRT-1351: Use capability to exclude disruption tests"
  pkg/api/component_report.go
Labels: approved, lgtm, jira/valid-reference

#1446 Show test ID on test details report
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm

#1442 Update component readiness square icons
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/ComponentReadinessHelp.js
  sippy-ng/src/component_readiness/extreme-triaged.svg
  sippy-ng/src/component_readiness/extreme.svg
  sippy-ng/src/component_readiness/green-3.png
  sippy-ng/src/component_readiness/green-half-data.png
  sippy-ng/src/component_readiness/green-heart.png
  sippy-ng/src/component_readiness/green.png
  sippy-ng/src/component_readiness/green.svg
  sippy-ng/src/component_readiness/green_no_data.png
  sippy-ng/src/component_readiness/half.svg
  sippy-ng/src/component_readiness/improved.svg
  sippy-ng/src/component_readiness/none.svg
  sippy-ng/src/component_readiness/red-3.png
  sippy-ng/src/component_readiness/red-3d.png
  sippy-ng/src/component_readiness/red-question-mark.png
  sippy-ng/src/component_readiness/regressed-triaged.svg
  sippy-ng/src/component_readiness/regressed.svg
Labels: approved, lgtm

#1447 TRT-1442: Fix CR toolbar buttons on mobile devices
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
Labels: approved, lgtm, jira/valid-reference

#1440 TRT-1443: Add etcd-leaders section from openshift/origin repo to sippy intervals chart
  pkg/apis/api/interval.go
  sippy-ng/src/components/TimelineChart.js
  sippy-ng/src/prow_job_runs/ProwJobRun.js
Labels: approved, lgtm, jira/valid-reference

#1451 require jira bug for a regression allowance
  pkg/regressionallowances/intentional_4.15_regressions.go
  pkg/regressionallowances/types.go
Labels: approved, lgtm

#1454 OCPBUGS-27495: Add exception for 4.15 operator network condition test
  pkg/componentreadiness/resolvedissues/resolved_4.15_issues.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1448 TRT-1225: Allow user to force refresh the cache, add time/date to the API and pages
  pkg/api/component_report.go
  pkg/api/disruption_report.go
  pkg/api/utils.go
  pkg/apis/api/types.go
  pkg/apis/cache/cache.go
  pkg/sippyserver/metrics/metrics.go
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
  sippy-ng/src/component_readiness/CompReadyEnvCapability.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/component_readiness/GeneratedAt.js
Labels: approved, lgtm, jira/valid-reference

#1458 trt-1439: observability dashboards link
  sippy-ng/src/components/Sidebar.js
Labels: approved, lgtm, jira/valid-reference

#1457 Show test component in Jira
  sippy-ng/src/tests/TestAnalysis.js
  sippy-ng/src/tests/TestTable.js
Labels: approved, lgtm

#1460 TRT-1351: Unrevert ignore disruption change and fix typo
  pkg/api/component_report.go
Labels: approved, lgtm, jira/valid-reference
