Repository openshift/sippy, pull requests merged in 2024-07, with the labels that each got.

#1811 updated to handle new information in variant names
  sippy-ng/src/components/MiniCard.js
  sippy-ng/src/helpers.js
  sippy-ng/src/tests/TestByVariantTable.css
  sippy-ng/src/tests/TestByVariantTable.js
Labels: approved, lgtm

#1550 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, needs-ok-to-test, lgtm

#1821 trt-1712: Update triage for new variants
  hack/gen-resolved-issue.py
  hack/requirements.txt
  pkg/api/component_report.go
  pkg/apis/api/types.go
  pkg/componentreadiness/resolvedissues/types.go
Labels: approved, lgtm, jira/valid-reference

#1826 trt-1712: Target build cluster
  hack/gen-resolved-issue.md
  hack/gen-resolved-issue.py
Labels: approved, lgtm, jira/valid-reference

#1824 upkeep: updated table grid view
  sippy-ng/src/App.js
  sippy-ng/src/releases/Install.js
  sippy-ng/src/releases/Upgrades.js
  sippy-ng/src/tests/TestByVariantTable.js
Labels: approved, lgtm

#1838 Merge master to master-component-readiness branch
  .gitignore
  cmd/sippy/load.go
  cmd/sippy/serve.go
  config/openshift.yaml
  pkg/api/component_report.go
  pkg/api/health.go
  pkg/api/install.go
  pkg/api/job_runs.go
  pkg/api/jobs.go
  pkg/api/tests.go
  pkg/componentreadiness/resolvedissues/types.go
  pkg/dataloader/prowloader/bigqueryjobs.go
  pkg/dataloader/prowloader/prow.go
  pkg/dataloader/releaseloader/release_dates.go
  pkg/dataloader/variantsyncer/variantsyncer.go
  pkg/flags/mode.go
  pkg/sippyserver/server.go
  pkg/testidentification/no_variants.go
  pkg/testidentification/ocp_never_stable.txt
  pkg/testidentification/ocp_variants.go
  pkg/testidentification/ocp_variants_test.go
  pkg/testidentification/variants.go
  pkg/variantregistry/loader.go
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
  sippy-ng/README.md
  sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/Sidebar.js
  sippy-ng/src/components/MiniCard.js
  sippy-ng/src/helpers.js
  sippy-ng/src/jobs/JobTable.css
  sippy-ng/src/jobs/JobTable.js
  sippy-ng/src/tests/TestByVariantTable.css
  sippy-ng/src/tests/TestByVariantTable.js
  sippy-ng/src/tests/TestTable.css
  sippy-ng/src/tests/TestTable.js
Labels: approved, lgtm

#1842 Fix /payload jobs leaking into variant based component readiness
  pkg/api/component_report.go
Labels: approved, lgtm

#1843 Update regressionallowances to use resolvedissues TriageMatchVariants…
  pkg/componentreadiness/resolvedissues/types.go
  pkg/regressionallowances/types.go
Labels: approved, lgtm

#1839 Use new variant registry for component readiness
  hack/gen-resolved-issue.md
  hack/gen-resolved-issue.py
  hack/requirements.txt
  pkg/api/component_report.go
  pkg/api/component_report_test.go
  pkg/api/health.go
  pkg/api/install.go
  pkg/api/job_runs.go
  pkg/api/jobs.go
  pkg/api/tests.go
  pkg/api/utils.go
  pkg/apis/api/types.go
  pkg/componentreadiness/resolvedissues/types.go
  pkg/componentreadiness/tracker/tracker.go
  pkg/regressionallowances/types.go
  pkg/sippyserver/metrics/metrics.go
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/IncludeVariantCheckboxList.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/ReleaseSelector.js
  sippy-ng/src/prow_job_runs/ProwJobRun.js
Labels: approved, lgtm

#1703 TRT-1307: Component Readiness use new variant registry
  pkg/api/component_report.go
  pkg/api/component_report_test.go
  pkg/api/utils.go
  pkg/apis/api/types.go
  pkg/componentreadiness/resolvedissues/types.go
  pkg/componentreadiness/tracker/tracker.go
  pkg/regressionallowances/types.go
  pkg/sippyserver/metrics/metrics.go
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/IncludeVariantCheckboxList.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
Labels: do-not-merge/hold, jira/valid-reference

#1846 Revert variant registry changes to master-component-readiness branch
  config/openshift.yaml
  hack/gen-resolved-issue.md
  hack/gen-resolved-issue.py
  hack/requirements.txt
  pkg/api/component_report.go
  pkg/api/component_report_test.go
  pkg/api/health.go
  pkg/api/install.go
  pkg/api/job_runs.go
  pkg/api/jobs.go
  pkg/api/tests.go
  pkg/api/utils.go
  pkg/apis/api/types.go
  pkg/componentreadiness/resolvedissues/types.go
  pkg/componentreadiness/tracker/tracker.go
  pkg/regressionallowances/types.go
  pkg/sippyserver/metrics/metrics.go
  pkg/sippyserver/server.go
  sippy-ng/src/App.js
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/IncludeVariantCheckboxList.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/ReleaseSelector.js
  sippy-ng/src/prow_job_runs/ProwJobRun.js
  sippy-ng/src/releases/Install.js
  sippy-ng/src/releases/Upgrades.js
  sippy-ng/src/tests/TestByVariantTable.js
Labels: approved, lgtm

#1847 Wrap component readiness test names in code blocks
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm

#1850 TRT-1702: enrich RiskAnalysis results
  pkg/api/job_runs.go
  pkg/api/job_runs_test.go
  pkg/apis/api/types.go
  pkg/db/query/test_queries.go
  pkg/sippyserver/pr_commenting_processor.go
  pkg/sippyserver/server.go
  pkg/sippyserver/server_test.go
Labels: approved, lgtm, jira/valid-reference

#1865 Include and display regressed test pass rates
  pkg/api/component_report.go
  pkg/api/component_report_test.go
  pkg/apis/api/types.go
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
Labels: approved, lgtm

#1869 trt-1740: use valueGetter for variants column
  sippy-ng/src/component_readiness/RegressedTestsModal.js
Labels: approved, lgtm, jira/valid-reference

#1876 trt-1749: add perfscale variant owner
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
Labels: approved, lgtm, jira/valid-reference

#1882 TRT-1743: Remove flake from success count for test cases
  pkg/api/component_report.go
Labels: approved, lgtm, jira/valid-reference

#1827 TRT-1706: Add bigquery query label to all queries
  pkg/api/component_report.go
  pkg/api/disruption_report.go
  pkg/api/releases.go
  pkg/apis/api/types.go
  pkg/componentreadiness/tracker/tracker.go
  pkg/dataloader/bugloader/bugloader.go
  pkg/dataloader/prowloader/bigqueryjobs.go
  pkg/variantregistry/loader.go
  pkg/variantregistry/ocp.go
Labels: approved, lgtm, jira/valid-reference

#1885 trt-1750: Support artifact matching for triage selection
  hack/gen-resolved-issue.md
  hack/gen-resolved-issue.py
Labels: approved, lgtm, jira/valid-reference

#1895 NO-JIRA: fix relative sample start time
  hack/gen-resolved-issue.py
Labels: approved, lgtm, jira/valid-reference

#1898 Update filtering to allow for owners
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm

#1901 Remove qe from defaults
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm
