Repository openshift/sippy, pull requests merged in 2024-02, with the labels that each got.

#1469 TRT-1232: Use flat_variants in place of variant to generate consistent data bet…
  pkg/api/component_report.go
  pkg/api/component_report_test.go
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm, jira/valid-reference

#1482 OLM problems were resolved
  pkg/componentreadiness/resolvedissues/resolved_4.15_issues.go
Labels: approved, lgtm

#1475 TRT-1464 Migrate Sippy to Cobra commands
  .gitignore
  DEVELOPMENT.md
  Dockerfile
  Makefile
  cmd/sippy-daemon/main.go
  cmd/sippy/load.go
  cmd/sippy/main.go
  cmd/sippy/migrate.go
  cmd/sippy/refresh.go
  cmd/sippy/serve.go
  cmd/sippy/snapshot.go
  e2e-scripts/sippy-e2e-sippy-e2e-setup-commands.sh
  e2e-scripts/sippy-e2e-sippy-e2e-test-commands.sh
  embed.go
  main.go
  pkg/flags/bigquery.go
  pkg/flags/cache.go
  pkg/flags/config.go
  pkg/flags/daemon.go
  pkg/flags/github_commenter.go
  pkg/flags/google.go
  pkg/flags/mode.go
  pkg/flags/postgres.go
  pkg/synthetictests/empty_synthetic_tests.go
  pkg/testidentification/kube_variants.go
  resources/kube/kube-deploymentconfig.yaml
  resources/kube/kube-fetchdata-cronjob.yaml
  resources/kube/kube-postgres-secret.yaml
  resources/kube/kube-postgresql.yaml
  resources/kube/kube-pvc-data.yaml
  resources/kube/kube-service.yaml
  scripts/e2e.sh
  scripts/fetchdata-kube.sh
  scripts/fetchdata-testgrid.sh
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/CHANGELOG.md
Labels: approved, lgtm

#1487 Make sure sippy-daemon binary is in image
  Dockerfile
Labels: approved, lgtm

#1489 Revert cobra refactor
  .gitignore
  DEVELOPMENT.md
  Dockerfile
  Makefile
  cmd/sippy-daemon/main.go
  cmd/sippy/load.go
  cmd/sippy/main.go
  cmd/sippy/migrate.go
  cmd/sippy/refresh.go
  cmd/sippy/serve.go
  cmd/sippy/snapshot.go
  e2e-scripts/sippy-e2e-sippy-e2e-setup-commands.sh
  e2e-scripts/sippy-e2e-sippy-e2e-test-commands.sh
  embed.go
  main.go
  pkg/flags/bigquery.go
  pkg/flags/cache.go
  pkg/flags/config.go
  pkg/flags/daemon.go
  pkg/flags/github_commenter.go
  pkg/flags/google.go
  pkg/flags/mode.go
  pkg/flags/postgres.go
  pkg/synthetictests/kube_synthetic_tests.go
  pkg/testidentification/kube_variants.go
  resources/kube/kube-deploymentconfig.yaml
  resources/kube/kube-fetchdata-cronjob.yaml
  resources/kube/kube-postgres-secret.yaml
  resources/kube/kube-postgresql.yaml
  resources/kube/kube-pvc-data.yaml
  resources/kube/kube-service.yaml
  scripts/e2e.sh
  scripts/fetchdata-kube.sh
  scripts/fetchdata-testgrid.sh
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/CHANGELOG.md
Labels: approved, lgtm

#1498 Updating the location of `ci-search`
  .gitignore
  pkg/db/loader/issues.go
  sippy-ng/src/helpers.js
  sippy-ng/src/jobs/JobTable.js
  sippy-ng/src/tests/TestTable.js
Labels: approved, lgtm

#1501 filter techpreview -sno-fips-recert jobs
  pkg/api/component_report.go
Labels: approved, lgtm

#1205 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#1514 Silence job runs with known loki infra outage causing alerts to fail a test
  pkg/componentreadiness/resolvedissues/resolved_4.15_issues.go
Labels: approved, lgtm

#1518 Ignore more 4.15 failures in CR due to loki outage, add 4.16 runs to ignore as well
  hack/gen-resolved-issue.py
  pkg/componentreadiness/resolvedissues/resolved_4.15_issues.go
  pkg/componentreadiness/resolvedissues/resolved_4.16_issues.go
Labels: approved, lgtm

#1521 Add GA date for 4.15
  pkg/dataloader/releaseloader/release_dates.go
Labels: approved, lgtm
