Repository openshift/sippy, pull requests merged in 2024-09, with the labels that each got.

#1959 TRT-1784: Add variants for container runtime and cgroupsversion
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
Labels: approved, lgtm, jira/valid-reference

#1968 trt-1792: Add all regressions view to RegressedTestsModal.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/TriagedIncidentGroups.js
  sippy-ng/src/component_readiness/TriagedIncidentsPanel.js
  sippy-ng/src/component_readiness/TriagedVariants.js
Labels: approved, lgtm, jira/valid-reference

#1971 trt-1792: Add Jira Link, filter irrelevant incidents
  pkg/api/componentreadiness/component_report.go
  sippy-ng/src/component_readiness/TriagedIncidentGroups.js
Labels: approved, lgtm, jira/valid-reference

#1927 TRT-1574: Server side views UI
  config/views.yaml
  e2e-scripts/sippy-e2e-sippy-e2e-setup-commands.sh
  e2e-scripts/sippy-e2e-sippy-e2e-test-commands.sh
  pkg/api/componentreadiness/queryparamparser.go
  pkg/api/componentreadiness/queryparamparser_test.go
  pkg/api/jobrunintervals/job_run_intervals.go
  pkg/api/utils.go
  pkg/apis/api/componentreport/types.go
  pkg/apis/api/types.go
  pkg/flags/component_readiness.go
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyUtils.test.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/ViewPicker.js
  test/e2e/componentreadiness/componentreadiness_test.go
Labels: approved, lgtm, jira/valid-reference

#1976 TRT-1799: Support previous values for allowed base regressions
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/test_details.go
  pkg/regressionallowances/intentional_4.15_regressions.go
  pkg/regressionallowances/intentional_regressions.go
  pkg/regressionallowances/types.go
Labels: approved, lgtm, jira/valid-reference

#1986 TRT-1807: CVE-2024-45296 update path-to-regexp
  sippy-ng/package-lock.json
Labels: approved, lgtm, jira/valid-reference

#1990 Add QE views, and add some jobs to be owned by QE
  config/qe-views.yaml
  pkg/variantregistry/ocp.go
Labels: approved, lgtm

#1992 4.18 view should be comparing against 4.16 ga, not latest
  config/views.yaml
Labels: approved, lgtm

#1994 Support generating intentional regressions JSON output
  hack/gen-resolved-issue.md
  hack/gen-resolved-issue.py
Labels: approved, lgtm

#1977 TRT-1784: Add CGroupMode and ContainerRuntime variants to CR
  config/views.yaml
  pkg/api/componentreadiness/component_report.go
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm, jira/valid-reference

#1953 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#2000 TRT-1813: fix bug omitting some variants from test_details filter
  pkg/api/componentreadiness/test_details.go
Labels: approved, lgtm, jira/valid-reference

#2007 TRT-1808: fix flakes link to include variants in job runs filter
  sippy-ng/src/tests/TestTable.js
Labels: approved, lgtm, jira/valid-reference

#2008 Continue to next view after one encounters errors
  pkg/sippyserver/metrics/metrics.go
Labels: approved, lgtm

#2015 Regressions 4.17 merge resolve
  pkg/regressionallowances/intentional_regressions.go
  pkg/regressionallowances/regressions_4.17.json
Labels: approved, lgtm

#2018 Add a view for runc vs crun
  config/views.yaml
Labels: approved, lgtm
