Repository openshift/sippy, pull requests merged in 2024-08, with the labels that each got.

#1905 Server Side Views
  cmd/sippy/component_readiness.go
  cmd/sippy/serve.go
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/queryparamparser.go
  pkg/api/componentreadiness/queryparamparser_test.go
  pkg/api/disruption_report.go
  pkg/api/utils.go
  pkg/apis/api/types.go
  pkg/dataloader/releaseloader/release_dates.go
  pkg/flags/cache.go
  pkg/flags/component_readiness.go
  pkg/sippyserver/metrics/metrics.go
  pkg/sippyserver/server.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: approved, lgtm

#1908 NO-JIRA: add support for -multi- job names
  pkg/api/componentreadiness/queryparamparser_test.go
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
Labels: approved, lgtm, jira/valid-reference

#1909 TRT-1765: fix multi parsing for non-heterogeneous names
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
Labels: approved, lgtm, jira/valid-reference

#1925 TRT-1777: Use jobname for NetworkStack as origin cluster-data cannot detect dualstack yet
  pkg/variantregistry/ocp.go
Labels: approved, lgtm, jira/valid-reference

#1912 TRT-1619: cross-variant comparison UI
  sippy-ng/src/component_readiness/CheckboxList.css
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/GroupByCheckboxList.js
  sippy-ng/src/component_readiness/IncludeVariantCheckboxList.js
  sippy-ng/src/component_readiness/ReleaseSelector.js
Labels: approved, lgtm, jira/valid-reference

#1926 TRT-1619: cross-variant comparison - pre-refactoring API
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/queryparamparser.go
  pkg/api/componentreadiness/queryparamparser_test.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/utils.go
  pkg/apis/api/componentreport/types.go
  pkg/apis/api/types.go
  pkg/componentreadiness/resolvedissues/types.go
  pkg/componentreadiness/tracker/tracker.go
  pkg/flags/component_readiness.go
  pkg/regressionallowances/types.go
  pkg/sippyserver/metrics/metrics.go
  pkg/sippyserver/server.go
Labels: approved, lgtm, jira/valid-reference

#1940 TRT-1766: Set default sample start date in sync with week setter
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm, jira/valid-reference

#1944 npm audit fix
  sippy-ng/package-lock.json
Labels: approved, lgtm

#1938 trt-1666: Add view to show existing triaged incidents
  sippy-ng/package-lock.json
  sippy-ng/package.json
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/ComponentReadiness.css
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/TriagedIncidentGroups.js
  sippy-ng/src/component_readiness/TriagedIncidentsPanel.js
  sippy-ng/src/component_readiness/TriagedTestDetailRow.js
  sippy-ng/src/component_readiness/TriagedTestDetails.js
  sippy-ng/src/component_readiness/TriagedTestJobRuns.js
  sippy-ng/src/component_readiness/TriagedVariants.js
Labels: approved, lgtm, jira/valid-reference

#1819 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#1937 TRT-1619: variant cross-comparison api
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/queryparamparser.go
  pkg/api/componentreadiness/queryparamparser_test.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/utils.go
  pkg/apis/api/componentreport/types.go
  pkg/sippyserver/metrics/metrics.go
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/GeneratedAt.js
  sippy-ng/src/component_readiness/GroupByCheckboxList.js
  sippy-ng/src/component_readiness/IncludeVariantCheckboxList.js
Labels: approved, lgtm, jira/valid-reference

#1949 api bugfix: race condition in sample/base queries
  pkg/api/componentreadiness/test_details.go
Labels: approved, lgtm

#1950 Stop selecting override display flag by default on intervals charts
  sippy-ng/src/prow_job_runs/ProwJobRun.js
Labels: approved, lgtm

#1952 ui: hopefully fix weird CR state problems with variants
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm

#1955 trt-1788: Ensure IncludeVariants not otherwise referenced are part of test_details query
  pkg/api/componentreadiness/test_details.go
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
Labels: approved, lgtm, jira/valid-reference

#1958 test_details UI: correctly omit empty cross-compare
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm
