Repository openshift/sippy, pull requests merged in 2024-03, with the labels that each got.

#1530 Migrate should use RunE instead of Run
  cmd/sippy/migrate.go
Labels: approved, lgtm

#1538 display the right dep info when running make
  Makefile
Labels: approved, lgtm

#1515 TRT-1437: Automate alert update when new releases are introduced
  pkg/api/releases.go
  pkg/apis/api/types.go
  pkg/db/query/release_queries.go
  pkg/sippyserver/metrics/installupgradesuccess.go
  pkg/sippyserver/metrics/metrics.go
Labels: approved, lgtm, jira/valid-reference

#1510 Add a check for nil attrs on a PR
  pkg/sippyserver/pr_commenting_processor.go
Labels: approved, lgtm

#1512 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#1563 Triage icons (Justin's Version)
  sippy-ng/src/component_readiness/extreme-triaged.svg
  sippy-ng/src/component_readiness/green-bypassed.svg
  sippy-ng/src/component_readiness/regressed-triaged.svg
Labels: approved, lgtm

#1546 TRT-1463: use bigquery to get releases for component readiness
  pkg/api/releases.go
  pkg/api/utils.go
  pkg/db/query/release_queries.go
  pkg/sippyserver/metrics/metrics.go
  pkg/sippyserver/server.go
Labels: approved, lgtm, jira/valid-reference

#1566 Improve bug handling in component readiness
  sippy-ng/src/bugs/BugButton.js
  sippy-ng/src/bugs/BugTable.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/tests/TestAnalysis.js
Labels: approved, lgtm

#1540 TRT-1484: Migrate bugloader to use bigquery data sources
  cmd/sippy/load.go
  pkg/dataloader/bugloader/bugloader.go
  pkg/dataloader/bugloader/bugloader_test.go
Labels: approved, lgtm, jira/valid-reference

#1567 Allow affects version to be nil
  sippy-ng/src/bugs/BugTable.js
Labels: approved, lgtm

#1571 TRT-1585: Add two new component readiness metrics
  pkg/sippyserver/metrics/metrics.go
Labels: approved, lgtm, jira/valid-reference

#1572 Fix install success metrics releaseStatus label
  pkg/sippyserver/metrics/installupgradesuccess.go
  pkg/sippyserver/metrics/metrics.go
Labels: approved, lgtm

#1569 Revert "TRT-1484: Migrate bugloader to use bigquery data sources"
  cmd/sippy/load.go
  pkg/dataloader/bugloader/bugloader.go
  pkg/dataloader/bugloader/bugloader_test.go
Labels: approved, lgtm, jira/valid-reference

#1575 Remove cache for releases API so that last updated timestamp is up to…
  pkg/sippyserver/server.go
Labels: approved, lgtm
