Repository openshift/sippy, pull requests merged in 2024-12, with the labels that each got.

#2144 Touchups for the triage script
  hack/gen-resolved-issue.py
Labels: approved, lgtm

#2139 TRT-1864: enable 4.19 views
  config/views.yaml
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm, jira/valid-reference

#2150 TRT-1781: sanitize sippy-server parameter inputs
  OWNERS
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/queryparamparser.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/job_analysis.go
  pkg/api/job_runs.go
  pkg/api/jobs.go
  pkg/api/tests.go
  pkg/api/utils.go
  pkg/filter/filterable.go
  pkg/sippyserver/install_details.go
  pkg/sippyserver/parameters.go
  pkg/sippyserver/server.go
  pkg/util/param/param.go
Labels: approved, lgtm, jira/valid-reference

#2165 trt-1795: add chaos job support
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
Labels: approved, lgtm, jira/valid-reference

#2167 component readiness: enforce techpreview in 4.19+
  config/views.yaml
Labels: approved, lgtm

#2166 Improve test reporting for feature gates
  pkg/apis/api/types.go
  pkg/db/query/feature_gates.go
  pkg/sippyserver/server.go
  sippy-ng/src/App.js
  sippy-ng/src/components/Sidebar.js
  sippy-ng/src/constants.js
  sippy-ng/src/helpers.js
  sippy-ng/src/releases/PayloadStreamsTable.js
  sippy-ng/src/releases/ReleaseOverview.js
  sippy-ng/src/tests/FeatureGates.js
  sippy-ng/src/tests/TestAnalysis.js
  sippy-ng/src/tests/TestTable.js
  sippy-ng/src/tests/Tests.js
Labels: approved, lgtm

#2170 Change base for 4.18-qe-main view to 4.17
  config/qe-views.yaml
Labels: approved, lgtm

#2162 Refactor component readiness query generators to generate entire queries
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/querygenerators.go
  pkg/api/componentreadiness/test_details.go
Labels: approved, lgtm

#2174 Revert "Merge pull request #2162 from dgoodwin/query-gen-refactor"
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/querygenerators.go
  pkg/api/componentreadiness/test_details.go
Labels: approved, lgtm

#2178 Restore GOLANG_VERSION and PATH
  Dockerfile.buildroot
Labels: approved, lgtm

#2177 Fix ROSA Variants
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
Labels: approved, lgtm

#2179 Festive Sippy
  sippy-ng/src/sippy.svg
Labels: approved, lgtm

#2074 TRT-1338: Potential replacement for the remaining 35 minute matview: Test analysis by job
  cmd/sippy/load.go
  pkg/api/test_analysis.go
  pkg/dataloader/bugloader/bugloader.go
  pkg/dataloader/prowloader/bigqueryjobs.go
  pkg/dataloader/prowloader/prow.go
  pkg/dataloader/prowloader/prow_test.go
  pkg/db/db.go
  pkg/db/models/prow.go
  pkg/db/partitionedtables.go
  pkg/db/query/job_queries.go
  pkg/db/query/test_queries.go
  pkg/db/views.go
Labels: approved, lgtm, jira/valid-reference

#2180 Revert "TRT-1338: Potential replacement for the remaining 35 minute matview: Test analysis by job"
  cmd/sippy/load.go
  pkg/api/test_analysis.go
  pkg/dataloader/bugloader/bugloader.go
  pkg/dataloader/prowloader/bigqueryjobs.go
  pkg/dataloader/prowloader/prow.go
  pkg/dataloader/prowloader/prow_test.go
  pkg/db/db.go
  pkg/db/matviews.go
  pkg/db/models/prow.go
  pkg/db/partitionedtables.go
  pkg/db/query/job_queries.go
  pkg/db/query/test_queries.go
Labels: approved, lgtm, jira/valid-reference

#2181 Use default go version from dnf install
  Dockerfile.buildroot
Labels: approved, lgtm

#2184 Add ROSA to 4.19-main dashboard
  config/views.yaml
Labels: approved, lgtm

#2183 by job analysis 2
  cmd/sippy/load.go
  pkg/api/test_analysis.go
  pkg/dataloader/bugloader/bugloader.go
  pkg/dataloader/prowloader/bigqueryjobs.go
  pkg/dataloader/prowloader/prow.go
  pkg/dataloader/prowloader/prow_test.go
  pkg/db/db.go
  pkg/db/models/prow.go
  pkg/db/partitionedtables.go
  pkg/db/query/job_queries.go
  pkg/db/query/test_queries.go
  pkg/db/views.go
Labels: approved, lgtm

#2185 Refactor query generators (take 2)
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/querygenerators.go
  pkg/api/componentreadiness/test_details.go
Labels: approved, lgtm

#2189 Allow page loads when test analysis is empty
  sippy-ng/src/tests/TestPassRateCharts.js
  sippy-ng/src/tests/TestStackedChart.js
Labels: approved, lgtm

#2004 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, needs-ok-to-test, lgtm

#2175 TRT-1781: sql hygiene
  pkg/api/job_runs.go
  pkg/bigquery/client.go
  pkg/cache/bigquerycache/bigquery.go
  pkg/db/query/test_queries.go
Labels: approved, lgtm, jira/valid-reference

#2193 Fix a G
  sippy-ng/src/releases/PayloadStreamsTable.js
Labels: approved, lgtm

#2196 TRT-1924: address jsonJobRunRiskAnalysis panics
  pkg/api/job_runs.go
Labels: approved, lgtm, jira/valid-reference

#2194 Log fatal and exit on redis outage
  pkg/api/utils.go
Labels: approved, lgtm
