Repository openshift/sippy, pull requests merged in 2025-03, with the labels that each got.

#2381 add 'smg247' to approvers
  OWNERS
Labels: approved, lgtm

#2382 Enable jira automation for 4.19 and disable it for 4.18
  config/views.yaml
Labels: approved, lgtm

#2317 TRT-1703: Consider high risk evaluation result from other unrelated prs
  cmd/sippy-daemon/main.go
  pkg/api/job_runs.go
  pkg/api/job_runs_test.go
  pkg/sippyserver/pr_commenting_processor.go
  pkg/sippyserver/server.go
Labels: approved, lgtm, jira/valid-reference

#2383 TRT-1825: limit comment size for new tests
  pkg/sippyserver/pr_commenting_processor.go
Labels: approved, lgtm, jira/valid-reference

#2384 TRT-2025: Fix comp readiness failing to load when no view exists for current release
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm, jira/valid-reference

#2379 TRT-2017: Port regression tracking from bigquery to postgresql
  Dockerfile.buildroot
  cmd/sippy-daemon/main.go
  cmd/sippy/automatejira.go
  cmd/sippy/component_readiness.go
  cmd/sippy/trackregressions.go
  hack/go-lint.sh
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
  pkg/componentreadiness/jiraautomator/jiraautomator.go
  pkg/dataloader/prowloader/bigqueryjobs.go
  pkg/dataloader/prowloader/github/github_test.go
  pkg/dataloader/prowloader/prow.go
  pkg/db/db.go
  pkg/sippyserver/metrics/metrics.go
  pkg/sippyserver/server.go
  scripts/e2e.sh
  test/e2e/componentreadiness/regressiontracker/regressiontracker_test.go
Labels: approved, lgtm, jira/valid-reference

#2388 Only enable checks for gocritic we already enabled
  .golangci.yml
Labels: approved, lgtm

#2389 TRT-1879: Allow sorting on regressed since and last failure for tests modal
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
Labels: approved, lgtm, jira/valid-reference

#2390 Increase timeout for golangci-lint
  hack/go-lint.sh
Labels: approved, lgtm

#2380 TRT-1966: add accessibility-mode to component readiness
  sippy-ng/src/AccessibilityModeProvider.js
  sippy-ng/src/App.js
  sippy-ng/src/component_readiness/AccessibilityToggle.js
  sippy-ng/src/component_readiness/CompCapRow.js
  sippy-ng/src/component_readiness/CompCapTestRow.js
  sippy-ng/src/component_readiness/CompReadyCapsCell.js
  sippy-ng/src/component_readiness/CompReadyCell.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
  sippy-ng/src/component_readiness/CompReadyEnvCapability.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
  sippy-ng/src/component_readiness/CompReadyRow.js
  sippy-ng/src/component_readiness/CompReadyTestCell.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/CompSeverityIcon.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/Sidebar.js
  sippy-ng/src/component_readiness/blue.svg
  sippy-ng/src/component_readiness/extreme-orange-triaged.svg
  sippy-ng/src/component_readiness/extreme-orange.svg
  sippy-ng/src/component_readiness/half-blue.svg
  sippy-ng/src/component_readiness/none-blue.svg
  sippy-ng/src/component_readiness/orange-triaged.svg
  sippy-ng/src/component_readiness/orange.svg
Labels: approved, lgtm, jira/valid-reference

#2387 TRT-2028: Remove prow and GCS bucket flags from Sippy
  cmd/sippy-daemon/main.go
  cmd/sippy/automatejira.go
  cmd/sippy/component_readiness.go
  cmd/sippy/load.go
  cmd/sippy/serve.go
  cmd/sippy/variants_generate.go
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/query/querygenerators.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/jobrunintervals/job_run_intervals.go
  pkg/apis/api/componentreport/types.go
  pkg/apis/prow/prow.go
  pkg/componentreadiness/jiraautomator/jiraautomator.go
  pkg/dataloader/prowloader/bigqueryjobs.go
  pkg/dataloader/prowloader/prow.go
  pkg/db/models/prow.go
  pkg/flags/google.go
  pkg/flags/prow.go
  pkg/sippyserver/metrics/metrics.go
  pkg/sippyserver/server.go
  pkg/variantregistry/ocp.go
Labels: approved, lgtm, jira/valid-reference

#2386 Prep test details for middleware use
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/middleware/interface.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm

#2391 Fix group by problem in variant registry
  pkg/variantregistry/ocp.go
Labels: approved, lgtm

#2392 TRT-1591: don't crash on nil or improperly formatted time
  sippy-ng/src/datagrid/GridToolbarFilterItem.js
Labels: approved, lgtm, jira/valid-reference

#2393 Ensure we handle any google error
  pkg/api/jobrunintervals/job_run_intervals.go
  pkg/dataloader/prowloader/gcs/gcs_jobrun.go
  pkg/dataloader/prowloader/prow.go
  pkg/variantregistry/ocp.go
Labels: approved, lgtm

#2394 Detect new two node arbiter topology variant
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
Labels: approved, lgtm

#2397 Add validation for gcs credentials and clarify the development readme
  DEVELOPMENT.md
  cmd/sippy-daemon/main.go
  cmd/sippy/automatejira.go
  cmd/sippy/component_readiness.go
  cmd/sippy/serve.go
  cmd/sippy/trackregressions.go
  cmd/sippy/variants_generate.go
  pkg/flags/google.go
Labels: approved, lgtm

#2399 Fix missing regressed since values
  cmd/sippy/component_readiness.go
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
Labels: approved, lgtm

#2401 npm audit fix
  sippy-ng/package-lock.json
Labels: approved, lgtm

#2402 Classify vsphere-host-groups jobs as candidate
  pkg/variantregistry/ocp.go
Labels: approved, lgtm

#2400 NO-JIRA: qualify pr options with job table name
  pkg/api/componentreadiness/query/querygenerators.go
Labels: approved, lgtm, jira/valid-reference

#2404 Exclude konflux jobs from component readiness
  pkg/api/componentreadiness/query/querygenerators.go
  pkg/variantregistry/ocp.go
Labels: approved, lgtm

#2398 TRT-1540: add alert when no accepted or rejected results are found for the payload calendar
  sippy-ng/src/releases/PayloadCalendar.js
Labels: approved, lgtm, jira/valid-reference

#2395 OCPERT-33 add/refine qe view for releases 4.14+
  config/qe-views.yaml
Labels: approved, lgtm

#2406 trt-2039: restore triagedIncidentsFor call
  pkg/api/componentreadiness/component_report.go
Labels: approved, lgtm, jira/valid-reference

#2407 TRT-1983: Use JobTiers for selecting jobs in component readiness
  config/views.yaml
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/query/querygenerators.go
Labels: approved, lgtm, jira/valid-reference

#2405 TRT-2039: triage via test details urls
  hack/gen-resolved-issue.py
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
Labels: approved, lgtm, jira/valid-reference

#2408 TRT-2040: Tidy up sample count msg
  pkg/api/componentreadiness/component_report.go
Labels: approved, lgtm, jira/valid-reference

#2191 Automated - Update never-stable
  pkg/testidentification/ocp_never_stable.txt
Labels: approved, ok-to-test, lgtm

#2409 TRT-2047: CR UI Updates
  hack/gen-resolved-issue.py
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/test_details.go
  pkg/componentreadiness/resolvedissues/types.go
  sippy-ng/src/component_readiness/CompCapRow.js
  sippy-ng/src/component_readiness/CompReadyRow.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
Labels: approved, lgtm, jira/valid-reference

#2412 TRT-1983: Set release and job tier for presubmits
  pkg/variantregistry/ocp.go
Labels: approved, lgtm, jira/valid-reference

#2413 Parallelize job variant registry
  pkg/variantregistry/ocp.go
Labels: approved, lgtm

#2426 trt-2058: Show Triaged Issues in TestDetails
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
  sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
  sippy-ng/src/component_readiness/CompReadyTestPanel.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/TriagedTestJobRuns.js
Labels: approved, lgtm, jira/valid-reference

#2427 NO-JIRA: refactor accessibility mode to use context
  sippy-ng/src/App.js
  sippy-ng/src/component_readiness/CompCapRow.js
  sippy-ng/src/component_readiness/CompCapTestRow.js
  sippy-ng/src/component_readiness/CompReadyCapsCell.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
  sippy-ng/src/component_readiness/CompReadyEnvCapability.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
  sippy-ng/src/component_readiness/CompReadyRow.js
  sippy-ng/src/component_readiness/CompReadyTestCell.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompSeverityIcon.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/Sidebar.js
  sippy-ng/src/components/AccessibilityModeProvider.js
  sippy-ng/src/components/AccessibilityToggle.js
Labels: approved, lgtm, jira/valid-reference

#2438 Add nat-instance network access variant
  pkg/variantregistry/ocp.go
  pkg/variantregistry/ocp_test.go
Labels: approved, lgtm
