Repository openshift/sippy, pull requests merged in 2025-04, with the labels that each got.

#2450 OCPNODE-2315: Add usernamespace suite
  pkg/variantregistry/ocp.go
Labels: approved, lgtm, jira/valid-reference

#2439 API to enable querying job artifacts
  pkg/api/jobartifacts/apitypes.go
  pkg/api/jobartifacts/manager.go
  pkg/api/jobartifacts/query.go
  pkg/api/jobartifacts/query_test.go
  pkg/sippyserver/pr_commenting_processor_test.go
  pkg/sippyserver/pr_new_tests_worker_test.go
  pkg/sippyserver/server.go
  pkg/util/param/param.go
  pkg/util/testing.go
Labels: approved, lgtm

#2465 Add network access to sidebar
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
Labels: approved, lgtm

#2433 TRT-1936: Triage Phase 1
  cmd/sippy/component_readiness.go
  cmd/sippy/serve.go
  e2e-scripts/sippy-e2e-sippy-e2e-test-commands.sh
  hack/triage.py
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/api/componentreadiness/triage.go
  pkg/apis/api/componentreport/types.go
  pkg/dataloader/bugloader/bugloader.go
  pkg/db/db.go
  pkg/db/models/prow.go
  pkg/db/models/triage.go
  pkg/db/query/job_queries.go
  pkg/db/query/triage_queries.go
  pkg/flags/api.go
  pkg/sippyserver/capabilities.go
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  test/e2e/componentreadiness/componentreadiness_test.go
  test/e2e/componentreadiness/regressiontracker/regressiontracker_test.go
  test/e2e/componentreadiness/triage/triageapi_test.go
  test/e2e/jobs_test.go
  test/e2e/releases_test.go
  test/e2e/util/db.go
  test/e2e/util/e2erequest.go
Labels: approved, lgtm, jira/valid-reference

#2477 update linter to manage go 1.23
  .golangci.yml
  Dockerfile.buildroot
  hack/go-lint.sh
  pkg/api/componentreadiness/queryparamparser.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/componentreadiness/jiraautomator/jiraautomator.go
  pkg/dataloader/bugloader/bugloader.go
  pkg/dataloader/prowloader/gcs/gcs_authentication.go
  pkg/dataloader/prowloader/prow.go
  pkg/dataloader/testownershiploader/testownershiploader.go
  pkg/db/partitionedtables.go
  pkg/sippyserver/metrics/metrics.go
Labels: approved, lgtm

#2472 NO-JIRA: specify required flag when running in `ocp` mode
  DEVELOPMENT.md
Labels: approved, lgtm, jira/valid-reference

#2473 enrich test details results
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/query/querygenerators.go
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
Labels: approved, lgtm

#2478 NO-JIRA: use new function name to restore functionality
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
Labels: approved, lgtm, jira/valid-reference

#2480 change layout of `test_details` results
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
  sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
  sippy-ng/src/component_readiness/CompReadyTestPanel.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm

#2494 TRT-2080: Include dev start date with Release
  pkg/api/releases.go
  pkg/api/releases_test.go
  pkg/apis/api/types.go
  pkg/apis/sippy/v1/types.go
  pkg/sippyserver/server.go
Labels: approved, lgtm, jira/valid-reference

#2464 jobartifacts: readability, expand content matching
  pkg/api/jobartifacts/apitypes.go
  pkg/api/jobartifacts/content_line_matcher.go
  pkg/api/jobartifacts/content_line_matcher_test.go
  pkg/api/jobartifacts/manager.go
  pkg/api/jobartifacts/query.go
  pkg/api/jobartifacts/query_test.go
  pkg/sippyserver/server.go
  pkg/util/param/param.go
Labels: approved, lgtm

#2508 NO-JIRA: Match Product
  pkg/api/componentreadiness/component_report.go
Labels: approved, lgtm, jira/valid-reference

#2509 NO-JIRA: Adjust partial triage counts
  pkg/api/componentreadiness/component_report.go
Labels: approved, lgtm, jira/valid-reference

#2499 TRT-2045: add the ability to create a triage entry in the UI, and update modal accordingly
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/CompSeverityIcon.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/TriagedRegressionTestList.js
  sippy-ng/src/component_readiness/TriagedRegressions.js
  sippy-ng/src/component_readiness/TriagedTestsPanel.js
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#2515 test_details: include start time in job run data
  pkg/api/componentreadiness/query/querygenerators.go
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
Labels: approved, lgtm

#2517 TRT-2045: add a description field to `triage`
  pkg/db/models/triage.go
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/TriagedRegressions.js
Labels: approved, lgtm, jira/valid-reference

#2479 TRT-2037: Add 4.20 view and use 4.18 ga for 4.19 basis
  config/views.yaml
Labels: approved, lgtm, jira/valid-reference

#2522 TRT-2045: triages are only available if there is a postgres connection
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
Labels: approved, lgtm, jira/valid-reference

#2533 TRT-2045: display triages on test-details page
  pkg/api/componentreadiness/triage.go
  pkg/db/query/triage_queries.go
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm, jira/valid-reference

#2534 Regression Tracking + Improved Fallback Middleware
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/middleware/interface.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/componentreadiness/utils/utils.go
  pkg/apis/api/componentreport/types.go
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
Labels: approved, lgtm

#2538 Revert "Regression Tracking + Improved Fallback Middleware"
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/middleware/interface.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/componentreadiness/utils/utils.go
  pkg/apis/api/componentreport/types.go
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
Labels: approved, lgtm

#2539 Remove RHCOS version mismatch warnings
  pkg/api/health.go
  pkg/api/releases.go
  pkg/api/releases_test.go
Labels: approved, lgtm
