Repository openshift/sippy, pull requests merged in 2025-06, with the labels that each got.

#2635 bugloader refactor
  pkg/dataloader/bugloader/bugloader.go
  pkg/dataloader/testownershiploader/testownershiploader.go
Labels: approved, lgtm

#2669 Hide triaged resolved ci-infra regressions
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker_test.go
Labels: approved, lgtm

#2675 TRT-1787: use query params for selections within the regressed test modal
  sippy-ng/src/App.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/TriagedRegressionTestList.js
  sippy-ng/src/component_readiness/TriagedRegressions.js
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#2643 Instant Test Details
  cmd/sippy/load.go
  config/views.yaml
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/middleware/interface.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker_test.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
  pkg/api/componentreadiness/query/querygenerators.go
  pkg/api/componentreadiness/queryparamparser.go
  pkg/api/componentreadiness/queryparamparser_test.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/componentreadiness/utils/utils.go
  pkg/api/utils.go
  pkg/apis/api/componentreport/types.go
  pkg/componentreadiness/jiraautomator/jiraautomator.go
  pkg/dataloader/crcacheloader/crcacheloader.go
  pkg/flags/cache.go
  pkg/sippyserver/metrics/metrics.go
  pkg/util/param/param.go
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
Labels: approved, lgtm

#2682 Revert "TRT-1787: fix needless browser history updates"
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/TriagedRegressionTestList.js
  sippy-ng/src/component_readiness/TriagedRegressions.js
Labels: approved, lgtm, jira/valid-reference

#2683 TRT-2147: Improvements to triage pages
  sippy-ng/src/component_readiness/Triage.js
  sippy-ng/src/component_readiness/TriagedRegressions.js
  sippy-ng/src/helpers.js
Labels: approved, lgtm, jira/valid-reference

#2694 Change environment to include both variant names and values
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm

#2695 trt-2143: add olm catalog validation suite
  pkg/db/suites.go
Labels: approved, lgtm, jira/valid-reference

#2699 TRT-2146: Add to existing Triage from RegressedTestsModal
  sippy-ng/src/component_readiness/AddRegressionPanel.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/UpsertTriageModal.js
Labels: approved, lgtm, jira/valid-reference

#2680 TRT-2142: adjust CR for intentional regressions against the sample release
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
  pkg/regressionallowances/intentional_regressions.go
  pkg/regressionallowances/regressions_4.19.json
  pkg/regressionallowances/types.go
  scripts/add-intentional-regression.py
Labels: approved, lgtm, jira/valid-reference

#2701 Add 4.19 intentional regressions for azure node not ready
  pkg/regressionallowances/regressions_4.19.json
Labels: approved, lgtm

#2704 TRT-1474: log the user making a mutating triage request in preparation for auditing
  pkg/sippyserver/server.go
Labels: approved, lgtm, jira/valid-reference

#2708 TRT-2155: Remove old triage implementation (server side)
  hack/gen-resolved-issue.md
  hack/gen-resolved-issue.py
  hack/triage.py
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
  pkg/componentreadiness/resolvedissues/types.go
  pkg/dataloader/crcacheloader/crcacheloader.go
Labels: approved, lgtm, jira/valid-reference

#2709 TRT-2154: handle old test_details links
  sippy-ng/src/component_readiness/CompReadyVars.js
Labels: approved, lgtm, jira/valid-reference

#2700 TRT-2007: Annotate job runs with labels
  cmd/sippy/annotatejobruns.go
  cmd/sippy/main.go
  pkg/api/componentreadiness/query/querygenerators.go
  pkg/api/jobartifacts/query.go
  pkg/componentreadiness/jobrunannotator/jobrunannotator.go
Labels: approved, lgtm, jira/valid-reference

#2711 Add IR for watch requests needing a slight bump in 4.19
  pkg/regressionallowances/regressions_4.19.json
Labels: approved, lgtm

#2706 refactor of `test_details` analysis
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/componentreadiness/utils/utils.go
  pkg/apis/api/componentreport/types.go
Labels: approved, lgtm

#2712 TRT-2158: remove (now) defunct triage incident logic from the frontend
  sippy-ng/src/component_readiness/CompCapRow.js
  sippy-ng/src/component_readiness/CompReadyRow.js
  sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
  sippy-ng/src/component_readiness/CompReadyTestPanel.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/ComponentReadinessToolBar.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/TriagedIncidentGroups.js
  sippy-ng/src/component_readiness/TriagedIncidentsPanel.js
  sippy-ng/src/component_readiness/TriagedVariants.js
Labels: approved, lgtm, jira/valid-reference

#2713 Fix double url parameters
  sippy-ng/src/component_readiness/CompCapRow.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
Labels: approved, lgtm

#2719 regressionallowances: break regressions into dir structure
  pkg/regressionallowances/intentional_regressions.go
  pkg/regressionallowances/regressions/4.17/regressions_4.17.json
  pkg/regressionallowances/regressions/4.18/regressions_4.18.json
  pkg/regressionallowances/regressions/4.19/OCPBUGS-44757-node-lifecycle.json
  pkg/regressionallowances/regressions/4.19/OCPBUGS-57351-operators-watch-channels.json
  pkg/regressionallowances/regressions/OWNERS
  scripts/add-intentional-regression.py
Labels: approved, lgtm

#2716 more CR refactoring
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/middleware/list.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
  pkg/api/componentreadiness/test_details.go
  pkg/apis/api/componentreport/types.go
  pkg/regressionallowances/types.go
Labels: approved, lgtm

#2739 Update QE views for 4.19 and add 4.20 view
  config/qe-views.yaml
Labels: approved, lgtm

#2740 TRT-2007: Mass triaged followup work
  cmd/sippy/annotatejobruns.go
  pkg/componentreadiness/jobrunannotator/jobrunannotator.go
Labels: approved, lgtm, jira/valid-reference

#2757 TRT-2138: add soft-validation when user attempts to create a triage with a duplicate Jira
  sippy-ng/src/component_readiness/AddRegressionPanel.js
  sippy-ng/src/component_readiness/ExistingTriageSelector.js
  sippy-ng/src/component_readiness/TriageFields.js
Labels: approved, lgtm, jira/valid-reference
