Repository openshift/sippy, pull requests merged in 2025-05, with the labels that each got.

#2541 TRT-2045: don't show triaged tests list if there are none
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm, jira/valid-reference

#2543 Time filtering for intervals charts
  sippy-ng/src/App.js
  sippy-ng/src/prow_job_runs/IntervalsChart.js
Labels: approved, lgtm

#2520 TRT-2045: only display one of "Triaged Incidents" or "Triaged Tests" tabs
  sippy-ng/src/component_readiness/RegressedTestsModal.js
Labels: approved, lgtm, jira/valid-reference

#2544 Fix the interval chart time filtering logic
  sippy-ng/src/prow_job_runs/IntervalsChart.js
Labels: approved, lgtm

#2546 Display count of intervals by source
  sippy-ng/src/prow_job_runs/IntervalsChart.js
Labels: approved, lgtm

#2550 NO-JIRA: enable unused import linting
  sippy-ng/.eslintrc.js
  sippy-ng/package-lock.json
  sippy-ng/package.json
  sippy-ng/src/App.js
  sippy-ng/src/bugs/BugButton.js
  sippy-ng/src/build_clusters/BuildClusterDetails.js
  sippy-ng/src/build_clusters/BuildClusterTable.js
  sippy-ng/src/component_readiness/AdvancedOptions.js
  sippy-ng/src/component_readiness/CompCapTestRow.js
  sippy-ng/src/component_readiness/CompReadyEnvCapability.js
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyTestPanel.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.test.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/CopyPageURL.js
  sippy-ng/src/component_readiness/GeneratedAt.js
  sippy-ng/src/component_readiness/GroupByCheckboxList.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/TriagedTestDetails.js
  sippy-ng/src/components/Sidebar.js
  sippy-ng/src/datagrid/GridToolbarDownload.js
  sippy-ng/src/datagrid/GridToolbarViewSelector.js
  sippy-ng/src/datagrid/utils.js
  sippy-ng/src/helpers.js
  sippy-ng/src/index.js
  sippy-ng/src/jobs/JobStackedChart.js
  sippy-ng/src/jobs/Jobs.js
  sippy-ng/src/releases/InstallTopLevelIndicators.js
  sippy-ng/src/releases/ReleasePayloadDetails.js
  sippy-ng/src/repositories/RepositoriesTable.js
  sippy-ng/src/tests/FeatureGates.js
  sippy-ng/src/tests/TestAnalysis.js
  sippy-ng/src/tests/TestOutputs.js
  sippy-ng/src/tests/TestPassRateCharts.js
  sippy-ng/src/tests/Tests.js
Labels: approved, lgtm, jira/valid-reference

#2559 Regression Tracking + Fallback Middleware Improvements Attempt #3
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/middleware/interface.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances_test.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback_test.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/componentreadiness/utils/utils.go
  pkg/apis/api/componentreport/types.go
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
Labels: approved, lgtm

#2562 Fix page load error when explanations is null
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm

#2516 TRT-2073: test_details job artifact search
  pkg/api/jobartifacts/apitypes.go
  pkg/api/jobartifacts/manager.go
  pkg/api/jobartifacts/query.go
  pkg/api/jobartifacts/query_test.go
  sippy-ng/src/component_readiness/CompReadyTestDetailRow.js
  sippy-ng/src/component_readiness/CompReadyTestPanel.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/ComponentReadiness.css
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/JobArtifactQuery.js
  sippy-ng/src/helpers.js
Labels: approved, lgtm, jira/valid-reference

#2564 NO-JIRA: fix the test checkbox by updating the location of the regression_id in the JSON
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
Labels: approved, lgtm, jira/valid-reference

#2566 Fix another regression ID reference
  sippy-ng/src/component_readiness/CompReadyUtils.js
Labels: approved, lgtm

#2569 TRT-2100: import css directly to fix styling after unused import removal
  sippy-ng/src/jobs/Jobs.js
Labels: approved, lgtm, jira/valid-reference

#2570 TRT-2089: fully wire up regression tracking middleware on test_details
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
  pkg/api/componentreadiness/test_details.go
  pkg/sippyserver/server.go
Labels: approved, lgtm, jira/valid-reference

#2568 data.analyses[0].explanations: missed one
  sippy-ng/src/component_readiness/CompReadyTestReport.js
Labels: approved, lgtm

#2565 Fix time filters when changing files
  sippy-ng/src/prow_job_runs/IntervalsChart.js
Labels: approved, lgtm

#2571 NO-JIRA: set 4.19 jobs as candidate
  pkg/variantregistry/ocp.go
Labels: approved, lgtm, jira/valid-reference

#2576 Add feature-gates loader to default loaders
  cmd/sippy/load.go
Labels: approved, lgtm

#2575 TRT-2089: allow the ability to triage a test from the test_details report
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/TriageFields.js
  sippy-ng/src/component_readiness/UpsertTriageModal.js
Labels: approved, lgtm, jira/valid-reference

#2551 TRT-2056: Track more regression data and show last failure in triaged table
  pkg/api/componentreadiness/regressiontracker.go
  pkg/db/models/triage.go
  sippy-ng/src/component_readiness/TriagedRegressionTestList.js
  test/e2e/componentreadiness/regressiontracker/regressiontracker_test.go
Labels: approved, lgtm, jira/valid-reference

#2578 Triage Resolution
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/component_report_test.go
  pkg/api/componentreadiness/middleware/interface.go
  pkg/api/componentreadiness/middleware/regressionallowances/regressionallowances.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker_test.go
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/api/componentreadiness/test_details.go
  pkg/api/componentreadiness/utils/utils.go
  pkg/apis/api/componentreport/types.go
  pkg/db/models/triage.go
  pkg/db/query/triage_queries.go
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompSeverityIcon.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/fix_failed.svg
  sippy-ng/src/component_readiness/fix_failed_accessible.svg
  sippy-ng/src/component_readiness/fixed_waiting.svg
  sippy-ng/src/component_readiness/fixed_waiting_accessible.svg
  test/e2e/componentreadiness/triage/triageapi_test.go
Labels: approved, lgtm

#2432 TRT-1984: Replace sippy mat view with bigquery tables
  pkg/api/tests.go
  pkg/apis/api/types.go
  pkg/db/query/test_queries.go
  pkg/filter/filterable.go
  pkg/sippyserver/server.go
  pkg/testidentification/ocp_variants.go
  sippy-ng/src/App.js
  sippy-ng/src/constants.js
  sippy-ng/src/tests/TestTable.js
Labels: approved, lgtm, jira/valid-reference

#2594 TRT-2105: intervals for payload-job runs
  cmd/sippy-daemon/main.go
  cmd/sippy/component_readiness.go
  cmd/sippy/serve.go
  pkg/api/jobrunintervals/job_run_intervals.go
  pkg/apis/api/interval.go
  pkg/flags/google.go
  pkg/sippyserver/server.go
  sippy-ng/src/prow_job_runs/IntervalsChart.js
Labels: approved, lgtm, jira/valid-reference

#2588 TRT-2120: Enable sippy e2e db tests and prevent port collisions
  e2e-scripts/sippy-e2e-sippy-e2e-test-commands.sh
  pkg/api/componentreadiness/regressiontracker.go
Labels: approved, lgtm, jira/valid-reference

#2596 TRT-2111: Display triaged bug state and version
  pkg/dataloader/bugloader/bugloader.go
  pkg/db/models/prow.go
  sippy-ng/src/component_readiness/TriagedRegressions.js
Labels: approved, lgtm, jira/valid-reference

#2586 TRT-2101: improvements to jobartifacts backend
  pkg/api/jobartifacts/apitypes.go
  pkg/api/jobartifacts/content_line_matcher.go
  pkg/api/jobartifacts/content_line_matcher_test.go
  pkg/api/jobartifacts/manager.go
  pkg/api/jobartifacts/query.go
  pkg/api/jobartifacts/query_test.go
  pkg/cache/compressed/cache_test.go
  pkg/sippyserver/server.go
  pkg/util/testing.go
  sippy-ng/src/component_readiness/JobArtifactQuery.js
Labels: approved, lgtm, jira/valid-reference

#2598 TRT-2050: create a page for `triage` details and allow some simple edits
  sippy-ng/src/App.js
  sippy-ng/src/component_readiness/CompReadyTestReport.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/Triage.js
  sippy-ng/src/component_readiness/TriageFields.js
  sippy-ng/src/component_readiness/TriagedRegressionTestList.js
  sippy-ng/src/component_readiness/TriagedRegressions.js
  sippy-ng/src/component_readiness/UpsertTriageModal.js
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#2602 TRT-2110: Link triaged bugs after they're synced to our db
  pkg/dataloader/bugloader/bugloader.go
Labels: approved, lgtm, jira/valid-reference

#2604 TRT-2122: Fix last failure time picking up flakes
  pkg/api/componentreadiness/query/querygenerators.go
Labels: approved, lgtm, jira/valid-reference

#2603 minor beautification
  sippy-ng/src/component_readiness/CompReadyEnvCapabilities.js
  sippy-ng/src/component_readiness/CompReadyEnvCapability.js
  sippy-ng/src/component_readiness/CompReadyEnvCapabilityTest.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/JobArtifactQuery.js
  sippy-ng/src/component_readiness/Triage.js
  sippy-ng/src/component_readiness/TriageFields.js
  sippy-ng/src/component_readiness/UpsertTriageModal.js
  sippy-ng/src/components/SecureLink.js
  sippy-ng/src/prow_job_runs/IntervalsChart.js
Labels: approved, lgtm

#2609 Fix triaged and resolved regressions staying open forever
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker_test.go
Labels: approved, lgtm

#2617 Hypershift should be blocking in CR for 4.20+
  config/views.yaml
Labels: approved, lgtm

#2619 TRT-2044: bugloader: associate mapped tests with bugs
  pkg/dataloader/bugloader/bugloader.go
  pkg/db/models/prow.go
Labels: approved, lgtm, jira/valid-reference

#2579 MCO-1652: Add MCO suite tracking
  pkg/variantregistry/ocp.go
Labels: approved, lgtm, jira/valid-reference

#2627 Revert "TRT-2044: bugloader: associate mapped tests with bugs"
  pkg/dataloader/bugloader/bugloader.go
  pkg/db/models/prow.go
Labels: approved, lgtm, jira/valid-reference

#2631 unrevert TRT-2044: bugloader: associate mapped tests with bugs
  pkg/dataloader/bugloader/bugloader.go
  pkg/db/models/prow.go
Labels: approved, lgtm, jira/valid-reference

#2632 TRT-2050: allow the ability to delete triage records and remove regressions from them
  pkg/api/componentreadiness/triage.go
  pkg/sippyserver/server.go
  sippy-ng/src/component_readiness/AddRegressionPanel.js
  sippy-ng/src/component_readiness/Triage.js
  sippy-ng/src/component_readiness/TriagedRegressions.js
  sippy-ng/src/component_readiness/UpdateTriagePanel.js
  sippy-ng/src/component_readiness/UpsertTriageModal.js
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#2633 don't delete bugs anymore
  pkg/dataloader/bugloader/bugloader.go
  pkg/db/query/job_queries.go
  pkg/db/query/test_queries.go
Labels: approved, lgtm

#2649 TRT-2094: add a link to the test_details report for each triage record
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/RegressedTestsModal.js
  sippy-ng/src/component_readiness/RegressedTestsPanel.js
  sippy-ng/src/component_readiness/TriagedRegressionTestList.js
  sippy-ng/src/component_readiness/TriagedRegressions.js
  sippy-ng/src/component_readiness/TriagedTestsPanel.js
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#2652 TRT-2094: fix triage details page by wrapping in the CompReadyVarsProvider
  sippy-ng/src/App.js
Labels: approved, lgtm, jira/valid-reference
