Repository openshift/sippy, pull requests merged in 2025-07, with the labels that each got.

#2762 TRT-2166: add the triages to the analysis regression in post-analysis
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker.go
  pkg/api/componentreadiness/middleware/regressiontracker/regressiontracker_test.go
Labels: approved, lgtm, jira/valid-reference

#2765 NO-JIRA: set current-user on context when updating triage record via bugloader
  pkg/dataloader/bugloader/bugloader.go
Labels: approved, lgtm, jira/valid-reference

#2768 Fix test analysis links
  sippy-ng/src/helpers.js
Labels: approved, lgtm

#2769 TRT-2159: We missed including some junits where the jobs start and finish on di…
  pkg/dataloader/prowloader/prow.go
Labels: approved, lgtm, jira/valid-reference

#2764 TRT-2148: Allow multiple payloads to be used for sample
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/query/querygenerators.go
  pkg/api/componentreadiness/queryparamparser.go
  pkg/apis/api/componentreport/reqopts/types.go
  pkg/util/param/param.go
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ReleaseSelector.js
Labels: approved, lgtm, jira/valid-reference

#2782 NO-JIRA: Bump linter to 1.63.4
  Dockerfile.buildroot
  hack/go-lint.sh
Labels: approved, lgtm, jira/valid-reference

#2784 TRT-2192: Bump go version in go.mod to 1.24
  go.mod
  pkg/api/job_runs.go
  pkg/api/jobs.go
  pkg/cache/bigquerycache/bigquery.go
  pkg/componentreadiness/resolvedissues/types.go
  pkg/dataloader/bugloader/bugloader.go
  pkg/github/commenter/ghcommenter.go
  pkg/sippyserver/server.go
  pkg/synthetictests/ocp_synthetic_tests.go
  pkg/util/rate_limiter.go
  pkg/util/utils.go
Labels: approved, lgtm, jira/valid-reference

#2787 TRT-2191: Revert "Allow multiple payload to be used for sample"
  pkg/api/componentreadiness/component_report.go
  pkg/api/componentreadiness/query/querygenerators.go
  pkg/api/componentreadiness/queryparamparser.go
  pkg/apis/api/componentreport/reqopts/types.go
  pkg/util/param/param.go
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyUtils.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ReleaseSelector.js
Labels: approved, lgtm, jira/valid-reference

#2777 TRT-2179: Add an explicit cache key for release fallback to limit unnecessary cache misses
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
Labels: approved, lgtm, jira/valid-reference

#2793 TRT-2179: do not allow cache refresh to be forced for the `releasefallback` caching
  pkg/api/componentreadiness/middleware/releasefallback/releasefallback.go
Labels: approved, lgtm, jira/valid-reference

#2781 TRT-2167: migrate regression tracking to the load framework
  DEVELOPMENT.md
  cmd/sippy/load.go
  cmd/sippy/main.go
  cmd/sippy/trackregressions.go
  pkg/api/componentreadiness/regressiontracker.go
  pkg/dataloader/loaderwithmetrics/loaderwithmetrics.go
  pkg/dataloader/loaderwithmetrics/loaderwithmetrics_test.go
Labels: approved, lgtm, jira/valid-reference

#2796 Fix test analysis links again
  sippy-ng/src/component_readiness/TestDetailsReport.js
  sippy-ng/src/helpers.js
Labels: approved, lgtm

#2798 TRT-2182: add a link to triage details within simple triage button tooltip
  sippy-ng/src/bugs/BugTable.js
Labels: approved, lgtm, jira/valid-reference

#2797 NO-JIRA: remove `load-openshift-ci-bigquery` flag
  DEVELOPMENT.md
  cmd/sippy/load.go
  e2e-scripts/sippy-e2e-sippy-e2e-setup-commands.sh
  scripts/e2e.sh
Labels: approved, lgtm, jira/valid-reference

#2806 Fix logging for job run annotator to be more accurate
  pkg/componentreadiness/jobrunannotator/jobrunannotator.go
Labels: approved, lgtm

#2804 TRT-2136: find the most recently started test name for display in the report
  pkg/api/componentreadiness/query/querygenerators.go
Labels: approved, lgtm, jira/valid-reference

#2805 trt-2195: update x86-vs-arm view
  config/views.yaml
Labels: approved, lgtm, jira/valid-reference

#2803 Subcommand to seed test data and much faster e2e
  cmd/sippy/main.go
  cmd/sippy/seed_data.go
  scripts/e2e.sh
  test/e2e/componentreadiness/triage/triageapi_test.go
  test/e2e/util/e2erequest.go
Labels: approved, lgtm

#2808 Fix class generation logic in invert mode
  sippy-ng/src/datagrid/utils.js
Labels: approved, ok-to-test, lgtm

#2813 API-1802: intervals: show certificate rotation events
  sippy-ng/src/prow_job_runs/IntervalsChart.js
Labels: approved, lgtm, jira/valid-reference

#2742 TRT-1814: Upgrade to react-router v6
  sippy-ng/package-lock.json
  sippy-ng/package.json
  sippy-ng/src/App.js
  sippy-ng/src/build_clusters/BuildClusterOverview.js
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/NotYetImplemented.js
  sippy-ng/src/components/Histogram.js
  sippy-ng/src/index.js
  sippy-ng/src/jobs/JobStackedChart.js
  sippy-ng/src/jobs/JobTable.css
  sippy-ng/src/jobs/Jobs.js
  sippy-ng/src/prow_job_runs/IntervalsChart.js
  sippy-ng/src/releases/Install.js
  sippy-ng/src/releases/PayloadCalendar.js
  sippy-ng/src/releases/PayloadMiniCalendar.js
  sippy-ng/src/releases/PayloadStream.js
  sippy-ng/src/releases/ReleasePayloadDetails.js
  sippy-ng/src/releases/Upgrades.js
  sippy-ng/src/repositories/RepositoriesTable.js
  sippy-ng/src/tests/FeatureGates.js
  sippy-ng/src/tests/TestTable.css
  sippy-ng/src/tests/Tests.js
Labels: approved, lgtm, jira/valid-reference

#2817 Revert "TRT-1814: Upgrade to react-router v6"
  sippy-ng/package-lock.json
  sippy-ng/package.json
  sippy-ng/src/App.js
  sippy-ng/src/build_clusters/BuildClusterOverview.js
  sippy-ng/src/component_readiness/CompReadyMainInputs.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
  sippy-ng/src/component_readiness/NotYetImplemented.js
  sippy-ng/src/components/Histogram.js
  sippy-ng/src/index.js
  sippy-ng/src/jobs/JobStackedChart.js
  sippy-ng/src/jobs/JobTable.css
  sippy-ng/src/jobs/Jobs.js
  sippy-ng/src/prow_job_runs/IntervalsChart.js
  sippy-ng/src/releases/Install.js
  sippy-ng/src/releases/PayloadCalendar.js
  sippy-ng/src/releases/PayloadMiniCalendar.js
  sippy-ng/src/releases/PayloadStream.js
  sippy-ng/src/releases/ReleasePayloadDetails.js
  sippy-ng/src/releases/Upgrades.js
  sippy-ng/src/repositories/RepositoriesTable.js
  sippy-ng/src/tests/FeatureGates.js
  sippy-ng/src/tests/TestTable.css
  sippy-ng/src/tests/Tests.js
Labels: approved, lgtm, jira/valid-reference

#2833 TRT-2112: auto-resolve triages when we detect that the associated bug's status has moved to "Modified" or beyond
  pkg/dataloader/bugloader/bugloader.go
Labels: approved, lgtm, jira/valid-reference

#2836 TRT-2218: Centralize URL params in vars context
  sippy-ng/src/component_readiness/CompReadyCapCell.js
  sippy-ng/src/component_readiness/CompReadyCapsCell.js
  sippy-ng/src/component_readiness/CompReadyCell.js
  sippy-ng/src/component_readiness/CompReadyTestCell.js
  sippy-ng/src/component_readiness/CompReadyVars.js
  sippy-ng/src/component_readiness/CompTestRow.js
  sippy-ng/src/component_readiness/ComponentReadiness.js
Labels: approved, lgtm, jira/valid-reference

#2837 Auto-resolve triage when ON_QA i.e. in an accepted payload
  pkg/dataloader/bugloader/bugloader.go
Labels: approved, lgtm
